name: build-deploy-webapp-to-azure-with-az-login

on:
  push:
    branches: none
      # - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: mcghactions                     # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '03-app-dotnet'         # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                            # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 03-app-dotnet
        
    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
#      - name: dotnet build and publish
#        run: |
#         dotnet restore
#         dotnet build --configuration Release
#         dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
     
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      
      - name: logout
        run: |
          az logout
